### ISSUE TITLE
Call Queue crash on agent_checkout

### ISSUE THREAD

**Issue by system123** [adhearsion/electric_slide#16]
ES crashes when trying to checkout an agent that may already have ended their call, or if the current free agent list is empty. Checks need to be put in place to prevent the queue crashing when this occurs, rather just fail safely and silently.

[2015-02-26 14:42:28.961] ERROR Adhearsion::OutboundCall: a645f118-8605-41c3-87dc-747c6574eb5e@: <NoMethodError> undefined method `presence=' for nil:NilClass
	/var/void/shared/bundle/jruby/1.9/bundler/gems/electric_slide-4ab90efbd422/lib/electric_slide/call_queue.rb:58:in `checkout_agent'
	/var/void/shared/bundle/jruby/1.9/bundler/gems/electric_slide-4ab90efbd422/lib/electric_slide/call_queue.rb:138:in `check_for_connections'
	/var/void/shared/bundle/jruby/1.9/bundler/gems/electric_slide-4ab90efbd422/lib/electric_slide/call_queue.rb:162:in `enqueue'
	/var/void/shared/bundle/jruby/1.9/bundler/gems/electric_slide-4ab90efbd422/lib/electric_slide/call_queue.rb:226:in `ignoring_ended_calls'
	/var/void/shared/bundle/jruby/1.9/bundler/gems/electric_slide-4ab90efbd422/lib/electric_slide/call_queue.rb:157:in `enqueue'
	org/jruby/RubyKernel.java:1958:in `public_send'
	/var/void/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
	/var/void/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
	/var/void/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `handle_message'
	/var/void/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `task'

**Comment by bklang** [comment]
I'm pretty sure this has since been fixed. Please re-open if you see it again using the latest code.
