### ISSUE TITLE
Presence callback cannot access agent object, after hangup.

### ISSUE THREAD

**Issue by system123** [adhearsion/electric_slide#57]
I'm using Electric Slide with bridging and manual agent return. I require the presence callback for the agent going into "unavailable" state, in order to initiate a cleanup sequence in my code. The issue lies in the "bridged_agent_health_check" method.

```Ruby
agent.call.on_end do
  agent.call = nil
  queue.return_agent agent, :unavailable
end
```

The return_agent method fires the "on_presence_changed" callback with parameters: queue, agent_call, new_presence, old_presence

As can be seen the agent_call will be nil in this case, and thus I cannot access the agent object in the callback handler as I normally do "agent_call[:agent]".

I am happy to make the fix, just want to discuss the best solution. I would recommend we return the agent in all callbacks instead of agent_call. The call object can always be accessed via the agent object. Would this be an acceptable fix?

**Comment by bklang** [comment]
> As can be seen the agent_call will be nil in this case, and thus I cannot access the agent object in the callback handler as I normally do "agent_call[:agent]".

I'm confused by this. Yes, the `agent.call` will be nil, but the callback is being passed the `agent` object as the first argument. Doesn't that get you what you need?

**Comment by bklang** [comment]
Sorry, my previous comment was incorrect: the first argument is `agent_call`, as you wrote. However, the callback is executed with [`instance_exec`](https://github.com/adhearsion/electric_slide/blob/develop/lib/electric_slide/agent.rb#L42) inside the `Agent` class, so the `agent` instance should be `self`, right?

**Comment by system123** [comment]
Hmmm, I missed that detail. Yes the `agent` instance should be `self` then. I will try that to confirm and get back to you.

**Comment by system123** [comment]
`self` works as you describe. Thanks.
